version: '3.6'
services:
    apache:
        platform: linux/x86_64
        # Hostname for apache container to locate itself
        # change to fit current project
        hostname: onboarding-partout.localhost
        container_name: onboardin_partout_apache
        depends_on:
            - db
            - mail
        build:
            context: ./.docker/php_apache
        volumes:
            - "./:/var/www/html"

            - "./.docker/php_apache/000-default.conf:/etc/apache2/sites-available/000-default.conf"
            - "./.docker/php_apache/php.ini:/usr/local/etc/php/php.ini"
            - "./.docker/php_apache/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
            - "./.docker/php_apache/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini"
        environment:
            - "APACHE_RUN_USER=#1000"
            - "APACHE_RUN_GROUP=#1000"
            # For typo3 site configuration
            # - "TYPO3_CONTEXT=Development/Docker"
        ports:
            - 80:80
        restart: unless-stopped
    php_cli:
        container_name: onboardin_partout_php
        depends_on:
            - db
            - mail
        build:
            context: ./.docker/php_cli
        volumes:
            - "./:/var/www/html"
            - "./.docker/php_cli/php.ini:/usr/local/etc/php/php.ini"
            - "./.docker/php_apache/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
            - "./.docker/php_apache/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini"
        user: 1000:1000
    db:
        container_name: onboardin_partout_mysql
        image: mysql:5.6
        working_dir: /application
        restart: unless-stopped
        volumes:
            - "./.mysql:/var/shared"
            - "./database:/var/lib/mysql"
        command:
            - --character-set-server=utf8
            - --collation-server=utf8_unicode_ci
            - --sql_mode=
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=database
        ports:
            - 3306:3306
    node:
        container_name: onboardin_partout_node
        image: node:12.13.0
        working_dir: "/var/www/html"
        volumes:
            - "./:/var/www/html"
        user: 1000:1000
        ports:
            - 4000:3000
        command: 'tail -f /dev/null'
    db_pma:
        container_name: onboardin_partout_phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_USER: root
            PMA_PASSWORD: root
            UPLOAD_LIMIT: 300M
    mail:
        container_name: onboardin_partout_mailhog
        image: mailhog/mailhog:latest
        ports:
            - 1025:1025
            - 8025:8025
